data_read<- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data <- subset(data_read, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
hist(data1$Global_active_power,  xlab="Global Active Power (kilowatts)", ylab="Frequency", main = "Global Active Power", col="Red")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()